---
- hosts: localhost
  vars:
    mount_src: /dev/sda
    mount_path: /mnt
    hostname: arch
  tasks:
    - name: Synchronize clock via NTP for logging purposes
      command: timedatectl set-ntp true
    - name: Partition boot disk
      block:
        - name: Wipe install drive partitions
          command: find /dev -wholename "{{ mount_src }}" -exec wipefs --force --all {} \;
        - name: Create boot partition
          parted:
            device: "{{ mount_src }}"
            label: gpt
            number: 1
            part_end: 512MB
            name: boot
            flags: [boot, esp]
            state: present
        - name: Create swap partition
          parted:
            device: "{{ mount_src }}"
            label: gpt
            number: 2
            part_start: 512MB
            part_end: 8GB
            name: swap
            flags: [swap]
            state: present
        - name: Create root partition
          parted:
            device: "{{ mount_src }}"
            label: gpt
            number: 3
            part_start: 8GB
            part_end: 100%
            name: root
            state: present
    - name: Create EFI filesystem
      filesystem:
        dev: "{{ mount_src }}1"
        fstype: vfat
        opts: -F 32
        force: true
    - name: Create root filesystem
      filesystem:
        dev: "{{ mount_src }}3"
        fstype: btrfs
        opts: -f -L ROOT -m single
        force: true
    - name: Create Btrfs subvolumes
      block:
        - name: Mount root partition for subvolume creation
          command: mount "{{ mount_src }}"3 /mnt
        - name: Create root subvolume
          command: btrfs subvolume create /mnt/@
        - name: Create home subvolume
          command: btrfs subvolume create /mnt/@home
        - name: Create var subvolume
          command: btrfs subvolume create /mnt/@var
        - name: Create opt subvolume
          command: btrfs subvolume create /mnt/@opt
        - name: Create tmp subvolume
          command: btrfs subvolume create /mnt/@tmp
        - name: Create snapshots subvolume
          command: btrfs subvolume create /mnt/@.snapshots
        - name: Unmount root partition
          command: umount /mnt
    - name: Mount subvolumes and boot partition
      block:
        #- name: Clear Btrfs space cache if present
           #command: btrfs check --clear-cache v2 "{{ mount_src }}3"
           #ignore_errors: true
        - name: Mount root directory on subvolume
          mount:
            path: /mnt
            fstype: btrfs
            src: "{{ mount_src }}3"
            opts: noatime,compress=zstd,space_cache=v2,subvol=@
            state: mounted
            fstab: /mnt/etc/fstab
        - name: Mount boot directory on subvolume
          mount:
            path: /mnt/boot
            fstype: vfat
            src: "{{ mount_src }}1"
            state: mounted
            #fstab: /mnt/etc/fstab
            fstab: /mnt/etc/fstab
        - name: Mount home directory on subvolume
          mount:
            path: /mnt/home
            fstype: btrfs
            src: "{{ mount_src }}3"
            opts: noatime,compress=zstd,space_cache=v2,subvol=@home
            state: mounted
            fstab: /mnt/etc/fstab
        - name: Mount var directory on subvolume
          mount:
            path: /mnt/var
            fstype: btrfs
            src: "{{ mount_src }}3"
            opts: subvol=@var
            state: mounted
            fstab: /mnt/etc/fstab
        - name: Mount opt directory on subvolume
          mount:
            path: /mnt/opt
            fstype: btrfs
            src: "{{ mount_src }}3"
            opts: noatime,compress=zstd,space_cache=v2,subvol=@opt
            state: mounted
            fstab: /mnt/etc/fstab
        - name: Mount snapshot directory on subvolume
          mount:
            path: /mnt/.snapshots
            fstype: btrfs
            src: "{{ mount_src }}3"
            opts: noatime,compress=zstd,space_cache=v2,subvol=@.snapshots
            state: mounted
            fstab: /mnt/etc/fstab
    - name: Install Arch Linux
      #when: false
      command: >
        pacstrap /mnt
        base
        base-devel
        linux
        linux-firmware
        btrfs-progs
        networkmanager
        intel-ucode
        neovim
        openssh
        grub
        efibootmgr
        reflector
        sudo
        python
        lua
        man-pages
        man-db
        dhcpcd
    - name: Generate filesystem table
      #command: genfstab -U /mnt >> /mnt/etc/fstab
      command: genfstab -U /mnt >> /mnt/etc/fstab
    #- name: Arch-chroot into the install
      #command: arch-chroot /mnt
    - name: Set the timezone
      command: arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
      #command: ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
    - name: Sync the hardware clock
      command: arch-chroot /mnt hwclock --systohc
      #command: hwclock --systohc
    - name: Set locale information
      block:
        - name: Uncomment locale.gen line
          lineinfile:
            path: /mnt/etc/locale.gen
            search_string: '#en_US.UTF-8 UTF-8'
            line: 'en_US.UTF-8 UTF-8'
        - name: Set locale.conf language
          lineinfile:
            path: /mnt/etc/locale.conf
            line: LANG=en_US.UTF-8
            create: true
        - name: Generate locale(s)
          command: arch-chroot /mnt locale-gen
          #command: locale-gen
    - name: Set hostname
      lineinfile:
        path: /mnt/etc/hostname
        line: "{{ hostname }}"
        create: true
    - name: Create hosts file
      blockinfile:
        path: /mnt/etc/hosts
        content: |
          127.0.0.1 localhost
          ::1 localhost
          127.0.1.1 {{ hostname }}.localdomain {{ hostname }}
        create: true
    # requires to be arch-chrooted into the system???
    #- name: Enable NetworkManager
      #systemd:
        #service: NetworkManager
        #enabled: true
    - name: Enable NetworkManager service
      command: arch-chroot /mnt systemctl enable NetworkManager
    # requires OpenSSH to be installed
    - name: Enable sshd service
      command: arch-chroot /mnt systemctl enable sshd
    - name: Fix initramfs for Btrfs
      lineinfile:
        path: /mnt/etc/mkinitcpio.conf
        regex: ^HOOKS=
        line: HOOKS=(base keyboard udev autodetect modconf block keymap encrypt btrfs filesystems fsck)
    - name: Create new initramfs
      command: arch-chroot /mnt mkinitcpio -p linux
    - name: Set up GRUB bootloader
      block:
        - name: install GRUB
          command: arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
        - name: Create GRUB config
          command: arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
